### ISSUE TITLE
[BUG] Wifi Scan doesn't seem to work on Lilygo C1101

### ISSUE THREAD

**Issue by fromport** [CapibaraZero/fw#68]
Hardware: lilygo CC1101
Software: 0.5.2 (beta)

**Describe the bug**
Main menu : I select Wi-Fi -> get 3 options: Scan/ Sniff / Go back
I press Scan
see scanning take place, % goes to 100%, see all the different channels increase, ends with channel 13
![100-channel13](https://github.com/user-attachments/assets/806a61f0-235e-4b23-b382-3b9c3fe144eb)

Then Display shows "No network found."
![no_network](https://github.com/user-attachments/assets/b5ede4cc-3ab6-4cae-9303-7bda45a438b0)

Screenshot WifiAnalyzer app on android
![wifiscan](https://github.com/user-attachments/assets/55a5da17-0bc6-4b65-9814-caa74f6edfc0)

I have many IOT devices on 2.4Ghz, have 3 AP's with 2.4Ghz
Go back to menu, click on "sniff"
On the screen
**Sniffing packets...
Sniffed packets: 1
[save]**

Count does not increase

**To Reproduce**
See above

**Expected behavior**
See a list of available SSID's.
I saw it once. but never again.

**Comment by stylesuxx** [comment]
Same hardware - scanning works fine on my end.
I can scroll through the results just fine - would prefer to see a list of results though instead of having "cards" of each of them...

Hardware: lilygo CC1101
Firmware: [0.5.2 (beta)](https://github.com/CapibaraZero/fw/tree/0.5.2-2024_12_28_52) slightly more up to date though.

**Comment by fromport** [comment]
I just updated to the lated 0.5.2 beta (with the fix for #67 ).
Had to disconnect the battery so really from scratch, still nothing.
Could it be depending on the amount of AP's it find ? could you overload the results ?

**Comment by andreock** [comment]
it seems to be a recurrent problem of ESP32. I don't find a real solution yet. I already do `WiFi.disconnect(); delay()` then start the scan but sometimes it stills fail(also to me).

**Comment by andreock** [comment]
[capibaraZero_0_5_2_lilygo_t_embed_cc1101_def_wifi.zip](https://github.com/user-attachments/files/18267872/capibaraZero_0_5_2_lilygo_t_embed_cc1101_def_wifi.zip)
Can you try this one? It use recommanded settings by EspressIf(shorten channel time)

**Comment by andreock** [comment]
[capibaraZero_0_5_2_lilygo_t_embed_cc1101_wifi_fix2.zip](https://github.com/user-attachments/files/18267943/capibaraZero_0_5_2_lilygo_t_embed_cc1101_wifi_fix2.zip)
This one seems better in my opinion. It implements a fix that I found on official Espressif Github and fixes a bug about GUI and WiFiScan that sometimes wasn't synchronized so that GUI printed "No networks Found" even if networks was found.

**Comment by fromport** [comment]
While scanning it now "jumps" through all the channels and I can see them .
Nice.
I am going to try it a few more times and see if it will fo it all times.
So far I am really happy and impressed by your feedback and ability to fix things.
Thanks a lot !
